class DoctorModel {
  String? doctorName;
  String? speciality;
  String? hospital;
  String? ratings;
  String? ratingCount;
  String? experience;
  String? location;
  String? patient;
  String? availability;
  String? image;

  DoctorModel(
      {this.doctorName,
      this.speciality,
      this.hospital,
      this.ratings,
      this.ratingCount,
      this.experience,
      this.location,
      this.patient,
      this.availability,
      this.image});
}

List<DoctorModel> allDoctors = [
  DoctorModel(
      doctorName: 'Dr. Yusril Sp.Kom ',
      speciality: 'Komputer Specialist',
      hospital: 'RSUD Cibinong',
      ratings: '4.4',
      ratingCount: '70',
      experience: '7',
      location: 'Cibinong, Kab. Bogor',
      patient: '6000+',
      availability: 'Tue - Fri 09.00 AM - 08.00 PM',
      image: 'assets/images/menmini.png'),
  DoctorModel(
      doctorName: 'dr. M. Arif Kurniawan, Sp,An  FIP',
      speciality: 'Spesialis Anastesi',
      hospital: 'RSUD Cibinong',
      ratings: '4.8',
      ratingCount: '60',
      experience: '6',
      location: 'Cibinong, Kab. Bogor',
      patient: '4300+',
      availability: 'Monday - Thursday 10am - 5 pm',
      image: 'assets/images/drarief.JPG'),
  DoctorModel(
      doctorName: 'dr Gita Puspitasari',
      speciality: 'Dokter Umum',
      hospital: 'RSUD Cibinong',
      ratings: '4.5',
      ratingCount: '30',
      experience: '7',
      location: 'Cibinong, Kab. Bogor',
      patient: '4300+',
      availability: 'Sunday - Thursday 10am - 5 pm',
      image: 'assets/images/drgita.JPG'),
  DoctorModel(
      doctorName: 'dr. Martinasari lubis, MARS',
      speciality: 'Dokter Umum',
      hospital: 'RSUD Cibinong',
      ratings: '4.5',
      ratingCount: '30',
      experience: '7',
      location: 'Cibinong, Kab. Bogor',
      patient: '4300+',
      availability: 'Sunday - Thursday 10am - 5 pm',
      image: 'assets/images/drsari.png'),
  DoctorModel(
      doctorName: 'dr. Frengky Bermana, Sp.B',
      speciality: 'Spesialis Bedah',
      hospital: 'RSUD Cibinong',
      ratings: '4.5',
      ratingCount: '30',
      experience: '7',
      location: 'Cibinong, Kab. Bogor',
      patient: '4300+',
      availability: 'Sunday - Thursday 10am - 5 pm',
      image: 'assets/images/drfrengky.JPG'),
  DoctorModel(
      doctorName: 'drg. Jarvi Agung Safitri, Sp.KG',
      speciality: 'Spesialis Gigi',
      hospital: 'RSUD Cibinong',
      ratings: '4.5',
      ratingCount: '30',
      experience: '7',
      location: 'Cibinong, Kab. Bogor',
      patient: '4300+',
      availability: 'Sunday - Thursday 10am - 5 pm',
      image: 'assets/images/drjarvi.JPG'),
  DoctorModel(
      doctorName: 'dr. Fahmi Idrus Sp.JP. Fiha',
      speciality: 'Spesialis Jantung',
      hospital: 'RSUD Cibinong',
      ratings: '4.5',
      ratingCount: '30',
      experience: '7',
      location: 'Cibinong, Kab. Bogor',
      patient: '4300+',
      availability: 'Sunday - Thursday 10am - 5 pm',
      image: 'assets/images/drfahmi.JPG'),
  // DoctorModel(
  //     doctorName: 'Tarik Bin Aziz',
  //     speciality: 'Cardiology',
  //     hospital: 'RSUD Cibinong',
  //     ratings: '4.5',
  //     ratingCount: '30',
  //     experience: '7',
  //     location: 'Cibinong, Kab. Bogor',
  //     patient: '4500+',
  //     availability: 'Sunday - Thursday 10am - 5 pm',
  //     image: 'assets/images/dr_blish.png'),
  // DoctorModel(
  //     doctorName: 'Dr. Austin Borgmeyer',
  //     speciality: 'Cardiology',
  //     hospital: 'RSUD Cibinong',
  //     ratings: '4.5',
  //     ratingCount: '30',
  //     experience: '7',
  //     location: 'Cibinong, Kab. Bogor',
  //     patient: '4500+',
  //     availability: 'Sunday - Thursday 10am - 5 pm',
  //     image: 'assets/images/dr_blish.png'),
  // DoctorModel(
  //     doctorName: 'Dr. Yusril Sp.Kom ',
  //     speciality: 'Cancer Specialist',
  //     hospital: 'RSUD Cibinong',
  //     ratings: '4.4',
  //     ratingCount: '70',
  //     experience: '7',
  //     location: 'Cibinong, Kab. Bogor',
  //     patient: '6000+',
  //     availability: 'Tue - Fri 09.00 AM - 08.00 PM',
  //     image: 'assets/images/dr_joshia.png'),
  // DoctorModel(
  //     doctorName: 'Dr. Yusril Sp.Kom ',
  //     speciality: 'Cancer Specialist',
  //     hospital: 'RSUD Cibinong',
  //     ratings: '4.4',
  //     ratingCount: '70',
  //     experience: '7',
  //     location: 'Cibinong, Kab. Bogor',
  //     patient: '6000+',
  //     availability: 'Tue - Fri 09.00 AM - 08.00 PM',
  //     image: 'assets/images/dr_joshia.png'),
  // DoctorModel(
  //     doctorName: 'Dr. Bernard Bliss',
  //     speciality: 'Skin Speciality',
  //     hospital: 'RSUD Cibinong',
  //     ratings: '4.2',
  //     ratingCount: '60',
  //     experience: '6',
  //     location: 'Cibinong, Kab. Bogor',
  //     patient: '4300+',
  //     availability: 'Monday - Thursday 10am - 5 pm',
  //     image: 'assets/images/dr_blish.png'),
  // DoctorModel(
  //     doctorName: 'Dr. Aidan Allende',
  //     speciality: 'Cancer Speciality',
  //     hospital: 'RSUD Cibinong',
  //     ratings: '4.5',
  //     ratingCount: '30',
  //     experience: '7',
  //     location: 'Cibinong, Kab. Bogor',
  //     patient: '4300+',
  //     availability: 'Sunday - Thursday 10am - 5 pm',
  //     image: 'assets/images/dr_allenda.png'),
];
